In [2]:
import numpy as np

In [3]:
np.__version__

'2.4.1'

## Create & Read

#### 1D Array

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.ndim

1

In [8]:
arr1.size

5

### 2D Array

In [10]:
arr2 = np.array([[1,4,5],[6,7,8]])
arr2

array([[1, 4, 5],
       [6, 7, 8]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 3)

In [13]:
arr2.dtype

dtype('int64')

### 3D Array

In [15]:
arr3 = np.array([[[1,4,5],[6,7,8]],[[3,4,5],[5,7,8]],[[1,4,5],[6,7,8]]])
arr3

array([[[1, 4, 5],
        [6, 7, 8]],

       [[3, 4, 5],
        [5, 7, 8]],

       [[1, 4, 5],
        [6, 7, 8]]])

In [16]:
arr3.ndim

3

In [17]:
arr3.shape

(3, 2, 3)